#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Tue May 03 11:19:16 2011

import wx
import zzMainFrame

if __name__ == "__main__":
	app = wx.PySimpleApp(0)	
	wx.InitAllImageHandlers()	
	frame_1 = zzMainFrame.zzMainFrame (None, -1, "")
	frame_1.Show(True)
	app.MainLoop()    